import { appendix, chapter, type MartinReadingPart } from './model';

const chapter10 = chapter(10, {"title":"Electronic Structure of Atoms","contribution":"Solves self-consistent one-electron equations in atomic geometry and prepares the radial functions used in pseudopotential and augmented methods.","core":"Atomic calculations provide the simplest self-consistent setting for Hartree–Fock and Kohn–Sham equations and generate ingredients reused in condensed-matter methods.","overview":"The chapter treats radial equations, spherical self-consistency, spin–orbit coupling, open shells, transition-element states, ΔSCF energies, and the atomic-sphere approximation. The emphasis is not a complete theory of atomic spectra, but the features that control transferable core–valence descriptions and atomic-like basis functions.","sections":["10.1 One-Electron Radial Schrödinger Equation","10.2 Independent-Particle Equations: Spherical Potentials","10.3 Spin–Orbit Interaction","10.4 Open-Shell Atoms: Nonspherical Potentials","10.5 Example of Atomic States: Transition Elements","10.6 Delta-SCF: Electron Addition, Removal, and Interaction Energies","10.7 Atomic Sphere Approximation in Solids"]});
const chapter11 = chapter(11, {"title":"Pseudopotentials","contribution":"Replaces chemically inert cores by transferable effective operators and connects OPW ideas to norm-conserving, ultrasoft, and PAW formulations.","core":"A pseudopotential preserves the low-energy scattering and valence physics of an all-electron atom while removing rapidly varying core behavior from the calculation.","overview":"Starting from phase shifts and orthogonalized plane waves, the chapter develops model and ab initio pseudopotentials, norm conservation, projectors, transferability, hardness, ultrasoft constructions, and PAW. It shows how different core treatments trade basis efficiency, all-electron reconstruction, and formal complexity.","sections":["11.1 Scattering Amplitudes and Pseudopotentials","11.2 Orthogonalized Plane Waves (OPWs) and Pseudopotentials","11.3 Model Ion Potentials","11.4 Norm-Conserving Pseudopotentials (NCPPs)","11.5 Generation of l-Dependent Norm-Conserving Pseudopotentials","11.6 Unscreening and Core Corrections","11.7 Transferability and Hardness","11.8 Separable Pseudopotential Operators and Projectors","11.9 Extended Norm Conservation: Beyond the Linear Regime","11.10 Optimized Norm-Conserving Potentials","11.11 Ultrasoft Pseudopotentials","11.12 Projector Augmented Waves (PAWs): Keeping the Full Wavefunction","11.13 Additional Topics"]});

export const partIII: MartinReadingPart = {
  id: "martin-part-iii",
  slug: "part-iii",
  route: "/reading/books/martin/part-iii/",
  numeral: "III",
  title: "Important Preliminaries on Atoms",
  summary: "Part III uses atomic geometry to illustrate self-consistent Hartree–Fock and Kohn–Sham equations and to construct the core–valence descriptions required by later solid-state methods.",
  progression: "Atomic radial and open-shell calculations first provide transferable atomic information; pseudopotential theory then replaces rapidly varying core behavior by effective valence operators, leading from scattering and OPW ideas to norm-conserving, ultrasoft, and PAW formulations.",
  units: [chapter10, chapter11],
};
