import { chapter, type MartinReadingPart } from './model';

const chapter19 = chapter(19, {"title":"Quantum Molecular Dynamics (QMD)","contribution":"Couples electronic forces to nuclear motion and explains Born–Oppenheimer, Car–Parrinello, and related first-principles molecular dynamics.","core":"Quantum molecular dynamics evolves nuclei on an electronic energy surface whose forces are computed from electronic structure at each stage of the trajectory.","overview":"The chapter develops Born–Oppenheimer dynamics, the Car–Parrinello unified electron–ion scheme, plane-wave expressions, non-self-consistent alternatives, and representative simulations. It highlights the algorithmic shift from diagonalization toward optimization, equations of motion, FFTs, and occupied-subspace operations.","sections":["19.1 Molecular Dynamics (MD): Forces from the Electrons","19.2 Born-Oppenheimer Molecular Dynamics","19.3 Car–Parrinello Unified Algorithm for Electrons and Ions","19.4 Expressions for Plane Waves","19.5 Non-self-consistent QMD Methods","19.6 Examples of Simulations"]});
const chapter20 = chapter(20, {"title":"Response Functions: Phonons and Magnons","contribution":"Connects energy derivatives and response functions to phonons, dielectric properties, electron–phonon coupling, superconductivity, and magnons.","core":"Small perturbations around equilibrium reveal material properties through derivatives of the electronic energy and the corresponding response functions.","overview":"The chapter moves from frozen displacements and spin rotations to density-response, Green-function, variational, and periodic-perturbation formulations. It covers phonon dispersions, effective charges, dielectric response, electron–phonon interactions, superconductivity, and spin-wave response.","sections":["20.1 Lattice Dynamics from Electronic Structure Theory","20.2 The Direct Approach: “Frozen Phonons,” Magnons","20.3 Phonons and Density Response Functions","20.4 Green’s Function Formulation","20.5 Variational Expressions","20.6 Periodic Perturbations and Phonon Dispersion Curves","20.7 Dielectric Response Functions, Effective Charges","20.8 Electron–Phonon Interactions and Superconductivity","20.9 Magnons and Spin Response Functions"]});
const chapter21 = chapter(21, {"title":"Excitation Spectra and Optical Properties","contribution":"Extends density-functional ideas to time-dependent perturbations and optical spectra of molecules, clusters, and crystals.","core":"Excitation spectra are obtained from the electronic response to time- or frequency-dependent fields, with TDDFT providing the central density-based framework.","overview":"The chapter introduces noninteracting dielectric response, linear-response and real-time TDDFT, time-dependent perturbation theory, and optical applications across finite and periodic systems. It closes by identifying the limitations of common adiabatic approximations.","sections":["21.1 Overview","21.2 Time-Dependent Density Functional Theory (TDDFT)","21.3 Dielectric Response for Noninteracting Particles","21.4 Time-Dependent DFT and Linear Response","21.5 Time-Dependent Density-Functional Perturbation Theory","21.6 Explicit Real-Time Calculations","21.7 Optical Properties of Molecules and Clusters","21.8 Optical Properties of Crystals","21.9 Beyond the Adiabatic Approximation"]});
const chapter22 = chapter(22, {"title":"Surfaces, Interfaces, and Lower-Dimensional Systems","contribution":"Applies band and electrostatic ideas to surfaces, interfaces, layered systems, and one-dimensional structures.","core":"Breaking three-dimensional periodicity creates potentials, states, and couplings that are localized at boundaries or confined to lower dimensions.","overview":"The chapter treats surface and interface potentials, Tamm and Shockley states, metal and semiconductor surfaces, semiconductor and oxide interfaces, layered materials, van der Waals structures, and nanotubes. Its examples connect boundary electronic structure to the topological surface states developed later.","sections":["22.1 Overview","22.2 Potential at a Surface or Interface","22.3 Surface States: Tamm and Shockley","22.4 Shockley States on Metals: Gold (111) Surface","22.5 Surface States on Semiconductors","22.6 Interfaces: Semiconductors","22.7 Interfaces: Oxides","22.8 Layer Materials","22.9 One-Dimensional Systems"]});
const chapter23 = chapter(23, {"title":"Wannier Functions","contribution":"Constructs localized representations of Bloch subspaces for interpolation, bonding analysis, reduced models, linear scaling, and topology.","core":"Wannier functions transform extended Bloch states into localized orbitals without losing the information contained in a chosen band subspace.","overview":"The chapter defines Wannier functions and their nonuniqueness, then develops projected, maximally localized, nonorthogonal, entangled-band, and hybrid forms. Applications show how they bridge first-principles bands to local chemistry, compact Hamiltonians, polarization, and topological analysis.","sections":["23.1 Definition and Properties","23.2 Maximally Projected Wannier Functions","23.3 Maximally Localized Wannier Functions","23.4 Nonorthogonal Localized Functions","23.5 Wannier Functions for Entangled Bands","23.6 Hybrid Wannier Functions","23.7 Applications"]});
const chapter24 = chapter(24, {"title":"Polarization, Localization, and Berry Phases","contribution":"Reformulates polarization and localization in periodic insulators through Berry phases and Wannier centers.","core":"Bulk polarization in a crystal is a geometric-phase property of occupied electronic states rather than a uniquely defined dipole moment of one unit cell.","overview":"The chapter explains why naive dipole formulas fail in extended systems, develops the Berry-phase theory of polarization, connects it to Wannier centers, and introduces localization measures, quantized pumping, and the polarization lattice. These ideas directly prepare the topology chapters.","sections":["24.1 Overview","24.2 Polarization: The Fundamental Difficulty","24.3 Geometric Berry Phase Theory of Polarization","24.4 Relation to Centers of Wannier Functions","24.5 Calculation of Polarization in Crystals","24.6 Localization: A Rigorous Measure","24.7 The Thouless Quantized Particle Pump","24.8 Polarization Lattice"]});

export const partV: MartinReadingPart = {
  id: "martin-part-v",
  slug: "part-v",
  route: "/reading/books/martin/part-v/",
  numeral: "V",
  title: "From Electronic Structure to Properties of Matter",
  summary: "Part V shows how ground-state electronic theory becomes a predictive description of motion, response, excitations, boundaries, localized band representations, polarization, and geometric phases.",
  progression: "The sequence moves from electron-derived forces and molecular dynamics to phonon, magnetic, dielectric, and optical response, then to surfaces and lower-dimensional systems. Wannier functions provide the localized bridge to the Berry-phase theory of polarization and to the topology developed in Part VI.",
  units: [chapter19, chapter20, chapter21, chapter22, chapter23, chapter24],
};
