import { appendix, type MartinReadingPart } from './model';

const appendixA = appendix("A", {"title":"Functional Equations","contribution":"Supplies variational calculus and functional-derivative machinery used in density-functional theory.","core":"Functional equations extend ordinary differentiation and variational stationarity to fields such as the electron density.","overview":"The appendix defines functionals, variations, Euler equations, constraints, and derivative rules, including density functionals with gradients. These formulas support the derivations of Kohn–Sham and semilocal functional equations.","sections":["A.1 Basic Definitions and Variational Equations","A.2 Functionals in Density Functional Theory Including Gradients"]});
const appendixB = appendix("B", {"title":"LSDA and GGA Functionals","contribution":"Collects explicit LSDA and GGA forms, including PBE, used in exchange–correlation calculations.","core":"Practical semilocal density-functional theory requires explicit spin-dependent local and gradient formulas for exchange and correlation energies and potentials.","overview":"The appendix summarizes LSDA, the general GGA structure, and the explicit PBE construction. It serves as a formula reference for Chapter 8 rather than as a separate survey of functionals.","sections":["B.1 Local Spin Density Approximation (LSDA)","B.2 Generalized-Gradient Approximation (GGAs)","B.3 GGAs: Explicit PBE Form"]});
const appendixC = appendix("C", {"title":"Adiabatic Approximation","contribution":"Defines the Born–Oppenheimer or adiabatic expansion and its role in phonons and electron–phonon coupling.","core":"The large nuclear mass separates fast electronic adjustment from slower nuclear motion and provides the small parameter behind the adiabatic approximation.","overview":"The appendix formulates the electronic–nuclear separation systematically and then applies it to electron–phonon interactions. It underpins the discussions of molecular dynamics, lattice dynamics, and superconductivity.","sections":["C.1 General Formulation","C.2 Electron-Phonon Interactions"]});
const appendixD = appendix("D", {"title":"Perturbation Theory, Response Functions, and Green’s Functions","contribution":"Provides common perturbative, response, Green-function, and 2n+1 relations used throughout the book.","core":"Perturbation theory and response functions translate changes in external fields into variations of quantum states and measurable observables.","overview":"The appendix covers static and dynamic response, self-consistent kernels, Kramers–Kronig relations, Green’s functions, and the 2n+1 theorem. It supplies the formal background for dielectric, phonon, and excitation calculations.","sections":["D.1 Perturbation Theory","D.2 Static Response Functions","D.3 Response Functions in Self-Consistent Field Theories","D.4 Dynamic Response and Kramers–Kronig Relations","D.5 Green’s Functions","D.6 The “2n + 1 Theorem”"]});
const appendixE = appendix("E", {"title":"Dielectric Functions and Optical Properties","contribution":"Defines dielectric and optical response in terms of fields, currents, densities, and lattice contributions.","core":"Dielectric functions connect electromagnetic perturbations to induced currents, polarization, and charge response in matter.","overview":"The appendix develops electromagnetic waves in media, conductivity and dielectric tensors, sum rules, longitudinal and transverse response, and ionic contributions. It provides the phenomenological bridge to the quantum calculations in Chapters 20, 21, and 24.","sections":["E.1 Electromagnetic Waves in Matter","E.2 Conductivity and Dielectric Tensors","E.3 The f-Sum Rule","E.4 Scalar Longitudinal Dielectric Functions","E.5 Tensor Transverse Dielectric Functions","E.6 Lattice Contributions to Dielectric Response"]});
const appendixF = appendix("F", {"title":"Coulomb Interactions in Extended Systems","contribution":"Resolves long-range Coulomb energy, potential references, Ewald sums, dipoles, and periodic-image effects.","core":"Extended charged systems require neutral, reference-consistent formulations so that Coulomb energies and potentials remain finite and physically comparable.","overview":"The appendix derives Ewald and smeared-ion expressions, energies relative to neutral atoms, surface and interface dipoles, and strategies for artificial image interactions. These issues are essential in periodic bulk, slab, interface, and supercell calculations.","sections":["F.1 Basic Issues","F.2 Point Charges in a Background: Ewald Sums","F.3 Smeared Nuclei or Ions","F.4 Energy Relative to Neutral Atoms","F.5 Surface and Interface Dipoles","F.6 Reducing Effects of Artificial Image Charges"]});
const appendixG = appendix("G", {"title":"Stress from Electronic Structure","contribution":"Derives the electronic contribution to macroscopic stress and internal strain.","core":"Stress is the tensor derivative of energy with respect to homogeneous strain and complements atomic forces in defining mechanical equilibrium.","overview":"The appendix relates stress and strain, derives pairwise and Fourier-space expressions, treats kinetic and Ewald contributions, and includes internal strain. It supports structural optimization and elastic-property calculations.","sections":["G.1 Macroscopic Stress and Strain","G.2 Stress from Two-Body Pair-Wise Forces","G.3 Expressions in Fourier Components","G.4 Internal Strain"]});
const appendixH = appendix("H", {"title":"Energy and Stress Densities","contribution":"Examines local energy and stress fields, their gauge freedom, and the integrated quantities that remain unique.","core":"Microscopic energy and stress densities are not unique, but carefully chosen integrals and fermionic contributions can still yield well-defined physical information.","overview":"The appendix develops alternative energy and stress densities, explains their nonuniqueness, and identifies invariant surface and integrated quantities. It also introduces the electron localization function as a related spatial diagnostic.","sections":["H.1 Energy Density","H.2 Stress Density","H.3 Integrated Quantities","H.4 Electron Localization Function (ELF)"]});
const appendixI = appendix("I", {"title":"Alternative Force Expressions","contribution":"Uses variational freedom to derive force, pressure, stress, and APW expressions beyond the standard Hellmann–Feynman form.","core":"At a variational minimum, first-order changes of electronic variables can be chosen to recast force derivatives into forms better suited to particular representations.","overview":"The appendix develops alternative energy-difference, pressure, force, and stress formulas, including treatments where core charge moves with nuclei and forms adapted to APW methods. The results clarify how equivalent force expressions arise.","sections":["I.1 Variational Freedom and Forces","I.2 Energy Differences","I.3 Pressure","I.4 Force and Stress","I.5 Force in APW-Type Methods"]});
const appendixJ = appendix("J", {"title":"Scattering and Phase Shifts","contribution":"Collects spherical scattering and phase-shift formulas used by pseudopotential and multiple-scattering methods.","core":"A localized spherical potential influences external waves through angular-momentum-dependent phase shifts.","overview":"The appendix relates radial solutions, scattering amplitudes, cross sections, and phase shifts. Its formulas support Chapter 11 pseudopotentials and Chapter 16 KKR and augmented methods.","sections":["J.1 Scattering and Phase Shifts for Spherical Potentials"]});
const appendixK = appendix("K", {"title":"Useful Relations and Formulas","contribution":"Provides special-function and angular-momentum identities repeatedly used in atomic and augmented representations.","core":"Bessel functions, spherical harmonics, coupling coefficients, and Chebyshev polynomials supply the mathematical basis for radial, angular, and polynomial expansions.","overview":"The appendix collects definitions and relations for Bessel, Neumann, Hankel, spherical-harmonic, Legendre, Clebsch–Gordan, Gaunt, and Chebyshev functions. It is a compact reference rather than a narrative chapter.","sections":["K.1 Bessel, Neumann, and Hankel Functions","K.2 Spherical Harmonics and Legendre Polynomials","K.3 Real Spherical Harmonics","K.4 Clebsch–Gordan and Gaunt Coefficients","K.5 Chebyshev Polynomials"]});
const appendixL = appendix("L", {"title":"Numerical Methods","contribution":"Collects numerical integration, minimization, mixing, quasi-Newton, and spectral-estimation tools used in electronic-structure algorithms.","core":"Electronic-structure calculations rely on iterative numerical methods chosen according to the conditioning, dimensionality, and structure of each subproblem.","overview":"The appendix covers Numerov integration, steepest descent, conjugate gradients, quasi-Newton methods, Pulay DIIS, Broyden updates, and moment or kernel-polynomial methods. These tools recur in orbital optimization, self-consistent-field mixing, and structural relaxation.","sections":["L.1 Numerical Integration and the Numerov Method","L.2 Steepest Descent","L.3 Conjugate Gradient","L.4 Quasi-Newton–Raphson Methods","L.5 Pulay DIIS Full-Subspace Method","L.6 Broyden Jacobian Update Methods","L.7 Moments, Maximum Entropy, Kernel Polynomial Method, and Random Vectors"]});
const appendixM = appendix("M", {"title":"Iterative Methods in Electronic Structure","contribution":"Specializes iterative eigensolvers and energy-minimization algorithms to large electronic-structure problems.","core":"Iterative subspaces, preconditioning, residual minimization, and energy minimization replace dense diagonalization when only a limited occupied subspace is needed.","overview":"The appendix develops relaxation, Krylov, Lanczos, Davidson, RMM–DIIS, constrained energy minimization, imaginary-time, and sparse or FFT complexity ideas. It explains the algorithmic foundations that made large plane-wave and real-space calculations practical.","sections":["M.1 Why Use Iterative Methods?","M.2 Simple Relaxation Algorithms","M.3 Preconditioning","M.4 Iterative (Krylov) Subspaces","M.5 The Lanczos Algorithm and Recursion","M.6 Davidson Algorithms","M.7 Residual Minimization in the Subspace – RMM–DIIS","M.8 Solution by Minimization of the Energy Functional","M.9 Comparison/Combination of Methods: Minimization of Residual or Energy","M.10 Exponential Projection in Imaginary Time","M.11 Algorithmic Complexity: Transforms and Sparse Hamiltonians"]});
const appendixN = appendix("N", {"title":"Two-Center Matrix Elements: Expressions for Arbitrary Angular Momentum l","contribution":"Gives a general angular-momentum construction for two-center matrix elements.","core":"Rotation algebra can express matrix elements between orbitals of arbitrary angular momenta in a bond-aligned frame.","overview":"The appendix derives a reusable formulation for transforming complex angular-momentum states and constructing two-center integrals beyond the low-l cases usually tabulated. It is primarily a technical reference for localized-orbital implementations.","sections":["General formulation for arbitrary angular momentum"]});
const appendixO = appendix("O", {"title":"Dirac Equation and Spin–Orbit Interaction","contribution":"Derives relativistic spin and spin–orbit terms from the Dirac equation and adapts them to atomic and solid-state calculations.","core":"The Dirac equation unifies relativity and spin, and its low-energy limit produces scalar-relativistic and spin–orbit effects central to heavy elements and topology.","overview":"The appendix introduces the four-component Dirac equation, obtains spin–orbit coupling in Schrödinger form, and develops atomic scalar-relativistic and spin–orbit treatments. It supplies the background used in magnetic, relativistic, and topological chapters.","sections":["O.1 The Dirac Equation","O.2 The Spin–Orbit Interaction in the Schrödinger Equation","O.3 Relativistic Equations and Calculation of the Spin–Orbit Interaction in an Atom"]});
const appendixP = appendix("P", {"title":"Berry Phase, Curvature, and Chern Numbers","contribution":"Derives Berry phase, connection, curvature, flux, and Chern number from quantum superposition.","core":"Geometric phase accumulated under parameter evolution leads to gauge-dependent connections and gauge-invariant curvature and topological integrals.","overview":"The appendix presents discrete and continuum Berry phases, curvature, Chern numbers, adiabatic evolution, the Aharonov–Bohm effect, and monopole analogies. Its formulas provide the mathematical foundation for polarization and topological band theory.","sections":["P.1 Overview","P.2 Berry Phase and Berry Connection","P.3 Berry Flux and Curvature","P.4 Chern Number and Topology","P.5 Adiabatic Evolution","P.6 Aharonov–Bohm Effect","P.7 Dirac Magnetic Monopoles and Chern Number"]});
const appendixQ = appendix("Q", {"title":"Quantum Hall Effect and Edge Conductivity","contribution":"Uses the quantum Hall effect to demonstrate Chern topology, edge transport, and bulk–boundary correspondence.","core":"Quantized Hall edge current is the boundary manifestation of an integer topological invariant of the bulk electronic states.","overview":"The appendix connects quantum Hall topology to chiral edge states and quantized conductivity. It provides the precedent for the boundary arguments used in topological insulators.","sections":["Q.1 Quantum Hall Effect and Topology","Q.2 Nature of the Surface States in the QHE"]});
const appendixR = appendix("R", {"title":"Codes for Electronic Structure Calculations for Solids","contribution":"Maps the book’s method families to representative solid-state electronic-structure codes.","core":"Electronic-structure implementations differ mainly through basis, core treatment, boundary conditions, response capabilities, and scaling strategy.","overview":"The appendix lists representative tutorial, plane-wave, APW, local-orbital, real-space, TDDFT, linear-scaling, Wannier, and structure-searching codes available when the edition was written. It is a publication-era implementation map, so present availability and capabilities require separate verification.","sections":["Tutorial codes","Plane-wave codes","(L)APW codes","Local-orbital codes","Real-space codes","Time-dependent DFT codes","Linear-scaling O(N) codes","Wannier-function tools","Structure-searching codes"]});

export const partVII: MartinReadingPart = {
  id: "martin-part-vii",
  slug: "part-vii",
  route: "/reading/books/martin/part-vii/",
  numeral: "VII",
  title: "Appendices",
  summary: "Part VII collects derivations, formulas, numerical tools, and physical background that support the main chapters but would interrupt their central narrative.",
  progression: "The source contains Appendices A–R as a broad technical reference. This deep-reading sequence follows O–Q because they complete the main book’s relativistic and topological argument: Dirac and spin–orbit structure lead into Berry geometry, then the quantum Hall effect supplies the clearest bulk–boundary example. The remaining technical appendices are best consulted from the chapters that invoke them rather than presented here as unfinished reading units.",
  units: [appendixA, appendixB, appendixC, appendixD, appendixE, appendixF, appendixG, appendixH, appendixI, appendixJ, appendixK, appendixL, appendixM, appendixN, appendixO, appendixP, appendixQ, appendixR],
};
