import { appendix, chapter, type MartinReadingPart } from './model';

const chapter12 = chapter(12, {"title":"Plane Waves and Grids: Basics","contribution":"Introduces the plane-wave and real-space representations that underpin modern periodic and grid-based electronic-structure algorithms.","core":"Plane waves and real-space grids are complementary representations linked by Fourier transforms and adapted to periodic and finite differential equations.","overview":"The chapter formulates the independent-particle equation in plane waves, revisits Bloch bands, and uses nearly-free-electron and empirical-pseudopotential models to build intuition. It then introduces density grids, finite differences, discontinuous Galerkin ideas, and multiresolution methods as preparation for full calculations.","sections":["12.1 The Independent-Particle Schrödinger Equation in a Plane Wave Basis","12.2 Bloch Theorem and Electron Bands","12.3 Nearly-Free-Electron Approximation","12.4 Form Factors and Structure Factors","12.5 Approximate Atomic-Like Potentials","12.6 Empirical Pseudopotential Method (EPM)","12.7 Calculation of Electron Density: Introduction of Grids","12.8 Real-Space Methods I: Finite Difference and Discontinuous Galerkin Methods","12.9 Real-Space Methods II: Multiresolution Methods"]});
const chapter13 = chapter(13, {"title":"Plane Waves and Real-Space Methods: Full Calculations","contribution":"Combines pseudopotentials, PAW, FFTs, iterative solution, screening, and supercells into practical self-consistent plane-wave and grid calculations.","core":"Full plane-wave and real-space calculations become practical when smooth core treatments, FFT-based operations, and iterative self-consistency are assembled into one method.","overview":"The chapter develops ab initio pseudopotential and PAW calculations, dielectric screening in the approach to self-consistency, exact exchange and hybrids in plane waves, and supercell treatments of surfaces, interfaces, dynamics, clusters, and molecules. It provides the bridge from representation basics to research calculations.","sections":["13.1 Ab initio Pseudopotential Method","13.2 Approach to Self-Consistency and Dielectric Screening","13.3 Projector Augmented Waves (PAWs)","13.4 Hybrid Functionals and Hartree–Fock in Plane Wave Methods","13.5 Supercells: Surfaces, Interfaces, Molecular Dynamics","13.6 Clusters and Molecules","13.7 Applications of Plane Wave and Grid Methods"]});
const chapter14 = chapter(14, {"title":"Localized Orbitals: Tight-Binding","contribution":"Builds an intuitive matrix description of bands and bonding from localized atomic orbitals and shows why few-band models remain powerful.","core":"Tight-binding reduces electronic structure to overlap and Hamiltonian matrix elements between localized orbitals, exposing how lattice geometry and orbital coupling create bands.","overview":"The chapter develops atom-centered orbitals, Slater–Koster forms, spin–orbit terms, one- and two-band models, graphene, nanotubes, CuO₂ planes, semiconductors, and transition metals. It also treats total energies, forces, nonorthogonality, and transferability, preparing both full localized-basis methods and later topological models.","sections":["14.1 Localized Atom-Centered Orbitals","14.2 Matrix Elements with Atomic-Like Orbitals","14.3 Spin–Orbit Interaction","14.4 Slater–Koster Two-Center Approximation","14.5 Tight-Binding Bands: Example of a Single s Band","14.6 Two-Band Models","14.7 Graphene","14.8 Nanotubes","14.9 Square Lattice and CuO₂ Planes","14.10 Semiconductors and Transition Metals","14.11 Total Energy, Force, and Stress in Tight-Binding","14.12 Transferability: Nonorthogonality and Environment Dependence"]});
const chapter15 = chapter(15, {"title":"Localized Orbitals: Full Calculations","contribution":"Turns the localized-orbital picture into quantitative self-consistent calculations with analytic, numerical, mixed, and Green-function bases.","core":"Localized bases can deliver efficient and accurate first-principles calculations, but their incompleteness and system dependence must be controlled explicitly.","overview":"The chapter formulates Kohn–Sham equations in nonorthogonal localized bases, compares Gaussian and numerical atomic orbitals, and discusses ground-state and excitation energies, forces, stress, recursion, Green functions, and mixed bases. Its central trade-off is efficiency and chemical transparency versus basis-specific convergence.","sections":["15.1 Solution of Kohn–Sham Equations in Localized Bases","15.2 Analytic Basis Functions: Gaussians","15.3 Gaussian Methods: Ground-State and Excitation Energies","15.4 Numerical Orbitals","15.5 Localized Orbitals: Total Energy, Force, and Stress","15.6 Applications of Numerical Local Orbitals","15.7 Green’s Function and Recursion Methods","15.8 Mixed Basis"]});
const chapter16 = chapter(16, {"title":"Augmented Functions: APW, KKR, MTO","contribution":"Develops augmented-wave, multiple-scattering, and muffin-tin-orbital methods that combine atomic behavior near nuclei with interstitial solutions.","core":"Augmented methods solve the electronic problem by matching atom-centered partial waves inside spheres to simpler functions in the interstitial region.","overview":"The chapter introduces APW and muffin-tin constructions, KKR multiple scattering, coherent-potential treatment of alloys, MTOs, canonical bands, localized reformulations, and total-energy derivatives. It shows the common scattering and augmentation structure behind several historically distinct all-electron methods.","sections":["16.1 Augmented Plane Waves (APWs) and “Muffin Tins”","16.2 Solving APW Equations: Examples","16.3 The KKR or Multiple-Scattering Theory (MST) Method","16.4 Alloys and the Coherent Potential Approximation (CPA)","16.5 Muffin-Tin Orbitals (MTOs)","16.6 Canonical Bands","16.7 Localized “Tight-Binding,” MTO, and KKR Formulations","16.8 Total Energy, Force, and Pressure in Augmented Methods"]});
const chapter17 = chapter(17, {"title":"Augmented Functions: Linear Methods","contribution":"Linearizes energy-dependent augmented functions to obtain practical LAPW and LMTO basis sets while retaining all-electron accuracy.","core":"Linear methods replace nonlinear energy dependence in augmented basis functions by expansions around selected energies, producing tractable generalized eigenvalue problems.","overview":"The chapter derives wavefunction energy derivatives and general linearized equations, then develops LAPW, LMTO, tight-binding variants, NMTO extensions, and full-potential treatments. The emphasis is how linearization converts powerful augmented constructions into reusable computational bases.","sections":["17.1 Linearization of Equations and Linear Methods","17.2 Energy Derivative of the Wavefunction: ψ and ψ̇","17.3 General Form of Linearized Equations","17.4 Linearized Augmented Plane Waves (LAPWs)","17.5 Applications of the LAPW Method","17.6 Linear Muffin-Tin Orbital (LMTO) Method","17.7 Tight-Binding Formulation","17.8 Applications of the LMTO Method","17.9 Beyond Linear Methods: NMTO","17.10 Full Potential in Augmented Methods"]});
const chapter18 = chapter(18, {"title":"Locality and Linear-Scaling O(N) Methods","contribution":"Uses nearsightedness, localized density matrices, and Wannier-like functions to reduce the scaling of electronic-structure calculations for large systems.","core":"For insulating and sufficiently local electronic systems, spatial decay permits observables to be computed without treating every pair of degrees of freedom globally.","overview":"The chapter explains the scaling bottleneck, physical locality, sparse Hamiltonian construction, nonvariational and variational density-matrix methods, localized-orbital approaches, self-consistent linear scaling, factorization, and hybrid strategies. It clarifies both the promise and the conditions behind O(N) methods.","sections":["18.1 What Is the Problem?","18.2 Locality in Many-Body Quantum Systems","18.3 Building the Hamiltonian","18.4 Solution of Equations: Nonvariational Methods","18.5 Variational Density Matrix Methods","18.6 Variational (Generalized) Wannier Function Methods","18.7 Linear-Scaling Self-Consistent Density Functional Calculations","18.8 Factorized Density Matrix for Large Basis Sets","18.9 Combining the Methods"]});

export const partIV: MartinReadingPart = {
  id: "martin-part-iv",
  slug: "part-iv",
  route: "/reading/books/martin/part-iv/",
  numeral: "IV",
  title: "Determination of Electronic Structure: The Basic Methods",
  summary: "Part IV compares the principal representations used to solve independent-particle equations in solids: plane waves and grids, localized atom-centered orbitals, augmented functions, linearized all-electron bases, and locality-based large-system methods.",
  progression: "The part advances from representation basics to full self-consistent calculations, contrasts delocalized and localized bases, develops scattering and augmentation approaches near nuclei, linearizes their energy dependence, and closes with the physical locality that can reduce computational scaling.",
  units: [chapter12, chapter13, chapter14, chapter15, chapter16, chapter17, chapter18],
};
