import { chapter, type MartinReadingPart } from './model';

const chapter25 = chapter(25, {"title":"Topology of the Electronic Structure of a Crystal: Introduction","contribution":"Introduces topological classification of crystal bands using Berry phases, curvature, Chern numbers, time-reversal symmetry, and bulk–boundary correspondence.","core":"Global properties of occupied Bloch states across the Brillouin zone can distinguish phases that cannot be connected without closing a gap or changing a protecting symmetry.","overview":"The chapter identifies what is being classified, relates bulk topology to boundary states, and assembles the Berry-phase formulas needed for crystals. It connects Chern numbers, time-reversal symmetry, Wannier functions, topological quantum chemistry, and Majorana ideas as an entry to explicit models.","sections":["25.1 Introduction","25.2 Topology of What?","25.3 Bulk-Boundary Correspondence","25.4 Berry Phase and Topology for Bloch States in the Brillouin Zone","25.5 Berry Flux and Chern Numbers: Winding of the Berry Phase","25.6 Time-Reversal Symmetry and Topology of the Electronic System","25.7 Surface States and the Relation to the Quantum Hall Effect","25.8 Wannier Functions and Topology","25.9 Topological Quantum Chemistry","25.10 Majorana Modes"]});
const chapter26 = chapter(26, {"title":"Two-Band Models: Berry Phase, Winding, and Topology","contribution":"Uses two-band Hamiltonians to make winding, Berry phases, band inversion, surface states, and the Thouless pump concrete.","core":"Two-band models reduce topological change to the geometry and winding of a vector multiplying the Pauli matrices.","overview":"The chapter develops one-dimensional two-site and s–p models, the Shockley transition, winding of Hamiltonians and Berry phases, two-dimensional Chern classification, cyclic adiabatic pumping, and graphene nanoribbons. It provides the simplest calculable route from band theory to a topological invariant.","sections":["26.1 General Formulation for Two Bands","26.2 Two-Band Models in One-Space Dimension","26.3 Shockley Transition in the Bulk Band Structure and Surface States","26.4 Winding of the Hamiltonian in One Dimension: Berry Phase and the Shockley Transition","26.5 Winding of the Berry Phase in Two Dimensions: Chern Numbers and Topological Transitions","26.6 The Thouless Quantized Particle Pump","26.7 Graphene Nanoribbons and the Two-Site Model"]});
const chapter27 = chapter(27, {"title":"Topological Insulators I: Two Dimensions","contribution":"Builds two-dimensional Chern and Z₂ insulators from spin–orbit-coupled models and connects them to realistic quantum wells and honeycomb lattices.","core":"Time-reversal symmetry and spin–orbit coupling permit a two-dimensional insulator to carry a Z₂ topology with protected edge states.","overview":"The chapter begins with Chern insulators and anomalous Hall physics, then develops the spin–orbit and time-reversal structure of Z₂ classification. Square-lattice, chain-to-plane, Hg/CdTe, graphene, and honeycomb models show how bulk topology and edge bands arise in model and real systems.","sections":["27.1 Two Dimensions: sp² Models","27.2 Chern Insulator and Anomalous Quantum Hall Effect","27.3 Spin–Orbit Interaction and the Diagonal Approximation","27.4 Topological Insulators and the Z₂ Topological Invariant","27.5 Example of a Topological Insulator on a Square Lattice","27.6 From Chains to Planes: Example of a Topological Transition","27.7 Hg/CdTe Quantum Well Structures","27.8 Graphene and the Two-Site Model","27.9 Honeycomb Lattice Model with Large Spin–Orbit Interaction"]});
const chapter28 = chapter(28, {"title":"Topological Insulators II: Three Dimensions","contribution":"Extends Z₂ topology to three dimensions and introduces strong and weak topological insulators, surface Dirac cones, Weyl nodes, and Fermi arcs.","core":"Three dimensions support four time-reversal topological indices and gapless Weyl phases whose boundary signatures have no isolated two-dimensional analogue.","overview":"The chapter distinguishes weak stacked-layer phases from robust strong topological insulators, develops tight-binding and Bi₂Se₃-based examples, and relates bulk indices to surface Dirac states. It then introduces Weyl and Dirac semimetals and the Fermi-arc surface states tied to bulk nodes.","sections":["28.1 Weak and Strong Topological Insulators in Three Dimensions: Four Topological Invariants","28.2 Tight-Binding Example in 3D","28.3 Normal and Topological Insulators in Three Dimensions: Sb₂Se₃ and Bi₂Se₃","28.4 Weyl and Dirac Semimetals","28.5 Fermi Arcs"]});

export const partVI: MartinReadingPart = {
  id: "martin-part-vi",
  slug: "part-vi",
  route: "/reading/books/martin/part-vi/",
  numeral: "VI",
  title: "Electronic Structure and Topology",
  summary: "Part VI introduces topological classification as a global property of Bloch states and develops the models and invariants needed to understand protected boundary states in two and three dimensions.",
  progression: "Berry phases, curvature, Chern numbers, time-reversal symmetry, and bulk–boundary correspondence are introduced first; two-band models then make winding and quantized pumping explicit, followed by two-dimensional Z₂ insulators and the weak, strong, and Weyl phases available in three dimensions.",
  units: [chapter25, chapter26, chapter27, chapter28],
};
