import { appendix, chapter, type MartinReadingPart } from './model';

const chapter6 = chapter(6, {"title":"Density Functional Theory: Foundations","contribution":"Establishes density as the basic variable and defines the exact ground-state framework that precedes any Kohn–Sham approximation.","core":"Density-functional theory states that the ground-state density determines the external potential and permits the ground-state energy to be obtained variationally from a universal density functional.","overview":"The chapter moves from Thomas–Fermi–Dirac ideas to the Hohenberg–Kohn theorems and the Levy–Lieb constrained search, then examines spin, finite-temperature, current, time-dependent, and polarization extensions. It also makes clear that existence theorems do not provide a practical expression for the universal functional.","sections":["6.1 Overview","6.2 Thomas–Fermi–Dirac Approximation","6.3 The Hohenberg–Kohn Theorems","6.4 Constrained Search Formulation of DFT","6.5 Extensions of Hohenberg–Kohn Theorems","6.6 Intricacies of Exact Density Functional Theory","6.7 Difficulties in Proceeding from the Density"]});
const chapter7 = chapter(7, {"title":"The Kohn–Sham Auxiliary System","contribution":"Turns exact density-functional theory into a calculable self-consistent auxiliary-particle problem and clarifies what its orbitals, eigenvalues, energies, forces, and potentials mean.","core":"The Kohn–Sham construction reproduces the interacting ground-state density with an auxiliary noninteracting system, leaving the unknown many-body effects in the exchange–correlation functional.","overview":"The chapter derives the Kohn–Sham variational equations, total- and free-energy functionals, self-consistent solution, mixing, forces and stress, and interpretations of the exchange–correlation potential and eigenvalues. It also marks the exact scope and unresolved intricacies of the auxiliary system.","sections":["7.1 Replacing One Problem with Another","7.2 The Kohn–Sham Variational Equations","7.3 Solution of the Self-Consistent Coupled Kohn–Sham Equations","7.4 Achieving Self-Consistency","7.5 Force and Stress","7.6 Interpretation of the Exchange–Correlation Potential Vxc","7.7 Meaning of the Eigenvalues","7.8 Intricacies of Exact Kohn–Sham Theory","7.9 Time-Dependent Density Functional Theory","7.10 Other Generalizations of the Kohn–Sham Approach"]});
const chapter8 = chapter(8, {"title":"Functionals for Exchange and Correlation I","contribution":"Explains the exchange–correlation hole and develops the local and generalized-gradient approximations that remain standard reference functionals.","core":"Local and semilocal functionals approximate exchange and correlation through the density and its gradients, guided by the physics of the exchange–correlation hole.","overview":"The chapter connects exchange and correlation energies to the reduced probability of finding another electron nearby, then develops LSDA, GGA, their potentials, and related average- or weighted-density approaches. Selected atomic, molecular, and solid examples show both the surprising success and systematic limits of locality.","sections":["8.1 Overview","8.2 Exc and the Exchange–Correlation Hole","8.3 Local (Spin) Density Approximation (LSDA)","8.4 How Can the Local Approximation Possibly Work As Well As It Does?","8.5 Generalized-Gradient Approximations (GGAs)","8.6 LDA and GGA Expressions for the Potential Vxc","8.7 Average and Weighted Density Formulations: ADA and WDA","8.8 Functionals Fitted to Databases"]});
const chapter9 = chapter(9, {"title":"Functionals for Exchange and Correlation II","contribution":"Extends density-functional theory beyond LDA and GGA through generalized Kohn–Sham, orbital-dependent, localized-correction, response-derived, and dispersion-inclusive functionals.","core":"More nonlocal information—often carried by orbitals, kinetic-energy density, response, or explicit long-range correlation—is needed when semilocal functionals cannot describe the target physics.","overview":"The chapter surveys hybrid and range-separated functionals, meta-GGAs, optimized effective potentials, self-interaction correction, DFT+U, response-based correlation, van der Waals functionals, and band-gap-oriented potentials. Its emphasis is the theoretical origin and applicability of each family rather than a catalogue of names.","sections":["9.1 Beyond the Local Density and Generalized Gradient Approximations","9.2 Generalized Kohn–Sham and Bandgaps","9.3 Hybrid Functionals and Range Separation","9.4 Functionals of the Kinetic Energy Density: Meta-GGAs","9.5 Optimized Effective Potential","9.6 Localized-Orbital Approaches: SIC and DFT+U","9.7 Functionals Derived from Response Functions","9.8 Nonlocal Functionals for van der Waals Dispersion Interactions","9.9 Modified Becke–Johnson Functional for Vxc","9.10 Comparison of Functionals"]});

export const partII: MartinReadingPart = {
  id: "martin-part-ii",
  slug: "part-ii",
  route: "/reading/books/martin/part-ii/",
  numeral: "II",
  title: "Density Functional Theory",
  summary: "Part II develops density-functional theory from its exact ground-state foundations to the Kohn–Sham auxiliary system and then to the exchange–correlation approximations that determine practical accuracy.",
  progression: "The argument begins by establishing the density as a valid basic variable, constructs a calculable self-consistent independent-particle system, and then examines how local, semilocal, orbital-dependent, response-based, and nonlocal functionals approximate the missing many-electron physics.",
  units: [chapter6, chapter7, chapter8, chapter9],
};
