import { chapter, type MartinReadingPart } from './model';

const chapter1 = chapter(1, {"title":"Introduction","contribution":"Establishes how quantum mechanics, independent-electron ideas, correlation, density-functional theory, materials design, and topology became the conceptual roots of modern electronic structure.","core":"Electronic-structure theory developed by turning the interacting electron–nucleus problem into calculable approximations while preserving the physics needed to explain and design materials.","overview":"The chapter compresses the path from the discovery of the electron and quantum mechanics to band theory, early quantitative calculations, electron correlation, density-functional theory, materials-by-design, and topological classification. Its role is historical and conceptual: it shows why present methods inherit both the power and the limitations of independent-particle pictures.","sections":["1.1 Quantum Theory and the Origins of Electronic Structure","1.2 Why Is the Independent-Electron Picture So Successful?","1.3 Emergence of Quantitative Calculations","1.4 The Greatest Challenge: Electron Interaction and Correlation","1.5 Density Functional Theory","1.6 Electronic Structure Is Now an Essential Part of Research","1.7 Materials by Design","1.8 Topology of Electronic Structure"]});
const chapter2 = chapter(2, {"title":"Overview","contribution":"Shows what electronic-structure theory is expected to explain across ground states, excitations, material classes, and thermodynamic conditions.","core":"This chapter defines the physical observables and material phenomena that the rest of the book must explain.","overview":"Using almost no formalism, the chapter surveys structural energetics, pressure, magnetism, elasticity, phonons, finite temperature, surfaces, low-dimensional systems, optical excitations, topology, and correlation. It defines the scientific targets that the later theory and algorithms are intended to reach.","sections":["2.1 Electronic Structure and the Properties of Matter","2.2 Electronic Ground State: Bonding and Characteristic Structures","2.3 Volume or Pressure As the Most Fundamental Variable","2.4 How Good Is DFT for Calculation of Structures?","2.5 Phase Transitions under Pressure","2.6 Structure Prediction: Nitrogen Solids and Hydrogen Sulfide Superconductors at High Pressure","2.7 Magnetism and Electron–Electron Interactions","2.8 Elasticity: Stress–Strain Relations","2.9 Phonons and Displacive Phase Transitions","2.10 Thermal Properties: Solids, Liquids, and Phase Diagrams","2.11 Surfaces and Interfaces","2.12 Low-Dimensional Materials and van der Waals Heterostructures","2.13 Nanomaterials: Between Molecules and Condensed Matter","2.14 Electronic Excitations: Bands and Bandgaps","2.15 Electronic Excitations and Optical Spectra","2.16 Topological Insulators","2.17 The Continuing Challenge: Electron Correlation"]});
const chapter3 = chapter(3, {"title":"Theoretical Background","contribution":"Collects the many-body equations, statistical framework, force and stress relations, and independent-particle approximations used throughout the book.","core":"A common quantum and statistical framework links the full interacting Hamiltonian to practical energies, densities, forces, stresses, and approximate one-electron descriptions.","overview":"The chapter sets out the electron–nuclear problem, Coulomb interactions, ground and excited states, density matrices, force and stress theorems, Hartree and Hartree–Fock approximations, and the distinction between exchange and correlation. It supplies the notation and formal relations needed for density-functional theory and computational methods.","sections":["3.1 Basic Equations for Interacting Electrons and Nuclei","3.2 Coulomb Interaction in Condensed Matter","3.3 Force and Stress Theorems","3.4 Generalized Force Theorem and Coupling Constant Integration","3.5 Statistical Mechanics and the Density Matrix","3.6 Independent-Electron Approximations","3.7 Exchange and Correlation"]});
const chapter4 = chapter(4, {"title":"Periodic Solids and Electron Bands","contribution":"Introduces the symmetry and reciprocal-space language that turns a periodic crystal into bands labeled by crystal momentum.","core":"Translational symmetry organizes electronic states into Bloch bands in the Brillouin zone, while time-reversal, inversion, and point symmetries further constrain those bands.","overview":"The chapter builds from lattice plus basis to reciprocal lattices and Brillouin zones, derives the Bloch classification of excitations, and discusses symmetry reduction, k-space integration, special points, and density of states. These ideas define the geometry used in calculations on periodic solids.","sections":["4.1 Structures of Crystals: Lattice + Basis","4.2 Reciprocal Lattice and Brillouin Zone","4.3 Excitations and the Bloch Theorem","4.4 Time-Reversal and Inversion Symmetries","4.5 Point Symmetries","4.6 Integration over the Brillouin Zone and Special Points","4.7 Density of States"]});
const chapter5 = chapter(5, {"title":"Uniform Electron Gas and sp-Bonded Metals","contribution":"Uses the homogeneous electron gas to isolate exchange, correlation, screening, and collective response before real ionic structure is added.","core":"The uniform electron gas is the simplest condensed-matter model in which the effects of Fermi statistics and Coulomb interaction can be studied as functions of density and spin polarization.","overview":"The chapter compares noninteracting and Hartree–Fock descriptions, introduces exchange and correlation holes, connects the electron gas to binding in sp-bonded metals, and develops the Lindhard dielectric response. The same system later becomes the reference behind local and semilocal density functionals.","sections":["5.1 The Electron Gas","5.2 Noninteracting and Hartree–Fock Approximations","5.3 Correlation Hole and Energy","5.4 Binding in sp-Bonded Metals","5.5 Excitations and the Lindhard Dielectric Function"]});

export const partI: MartinReadingPart = {
  id: "martin-part-i",
  slug: "part-i",
  route: "/reading/books/martin/part-i/",
  numeral: "I",
  title: "Overview and Background Topics",
  summary: "Part I frames electronic structure as an interacting-electron problem whose practical success depends on controlled independent-particle descriptions, then introduces the physical scope, theoretical language, periodic symmetry, and homogeneous-electron reference used throughout the book.",
  progression: "The sequence moves from historical origins and modern research goals to the many-body equations, then to Bloch states in crystals and finally to the electron gas, where exchange, correlation, screening, and simple-metal binding can be isolated before density-functional theory is introduced.",
  units: [chapter1, chapter2, chapter3, chapter4, chapter5],
};
