export type ResearchTopic = {
  id: string;
  title: string;
  centralQuestion: string;
  questions: string[];
  evidence: string;
  connections: { label: string; href: string }[];
};

export const researchTopics: ResearchTopic[] = [
  { id: 'structures-phase-competition', title: 'Structures, bonding, and phase competition', centralQuestion: 'Why does a particular structure form, and which structural or chemical state is stable under specified conditions?', questions: ['Which structures compete under the stated pressure, composition, strain, or temperature?', 'Which energetic, vibrational, or thermodynamic terms decide between them?'], evidence: 'Relative energies, forces and stresses, equations of state, phase diagrams, phonons, free energies, and structural measurements.', connections: [{ label: 'Foundations: Thermodynamics', href: '/theory/thermodynamics/' }, { label: 'Methods', href: '/methods/' }] },
  { id: 'electronic-character', title: 'Ground-state electronic character', centralQuestion: 'Why is the system metallic, semiconducting, insulating, localized, or otherwise electronically distinct?', questions: ['Which states define the low-energy electronic character?', 'Does that classification survive a change in approximation or comparison with experiment?'], evidence: 'Bands, densities of states, Fermi surfaces, orbital or spin projections, total-energy comparisons, and relevant measurements.', connections: [{ label: 'Foundations: Kohn–Sham DFT', href: '/theory/kohn-sham-density-functional-theory/' }, { label: 'Books', href: '/reading/books/' }] },
  { id: 'defects-disorder', title: 'Defects and disorder', centralQuestion: 'How do imperfections change energetics, charge states, electronic states, and material behavior?', questions: ['Which defects are thermodynamically accessible under specified reservoirs?', 'Which charge states, transition levels, or local structures change the observable of interest?'], evidence: 'Formation energies versus Fermi level, transition levels, relaxed structures, local states, finite-size tests, kinetics, and experiment.', connections: [{ label: 'Foundations: Solid-state chemistry', href: '/theory/solid-state-chemistry/' }, { label: 'Methods', href: '/methods/' }] },
  { id: 'interfaces-heterostructures', title: 'Surfaces, interfaces, and heterostructures', centralQuestion: 'What changes or emerges when two electronic environments meet?', questions: ['Which termination, registry, and electrostatic reference define the interface?', 'Which interface-specific observable distinguishes redistribution, hybridization, screening, or an emergent state?'], evidence: 'Formation energies, electrostatic potentials, projected or unfolded bands, density redistribution, localized states, response functions, and experiment.', connections: [{ label: 'Foundations: Surface and interface chemistry', href: '/theory/surface-and-interface-chemistry/' }, { label: 'Methods', href: '/methods/' }] },
  { id: 'magnetism-correlation', title: 'Magnetism and strong electronic correlation', centralQuestion: 'How do spin and electron–electron interactions create phases that a simple independent-particle picture cannot capture?', questions: ['Which competing spin, orbital, or correlated states must be compared?', 'What observable distinguishes a magnetic order, a local moment, and a correlation-driven spectrum?'], evidence: 'Magnetic energy differences, spin densities, exchange parameters, spectral functions, susceptibilities, and magnetic or spectroscopic measurements.', connections: [{ label: 'Foundations: Spin and magnetism', href: '/theory/relativistic-electronic-structure-spin-and-magnetism/' }, { label: 'Foundations: Many-body physics', href: '/theory/many-body-physics/' }] },
  { id: 'lattice-dynamics', title: 'Lattice dynamics and finite-temperature nuclei', centralQuestion: 'How does the lattice move, soften, become unstable, and change with temperature?', questions: ['Which collective displacement or phonon branch controls the question?', 'Where does the harmonic description end and finite-temperature nuclear physics begin?'], evidence: 'Force constants, dynamical matrices, phonon dispersions and eigenvectors, Raman or IR spectra, scattering, and anharmonic free energies.', connections: [{ label: 'Foundations: Linear response', href: '/theory/linear-response-and-excited-states/' }, { label: 'Methods', href: '/methods/' }] },
  { id: 'electron-phonon-superconductivity', title: 'Electron–phonon interaction and conventional superconductivity', centralQuestion: 'How do electrons interact with lattice vibrations, and when does that coupling produce scattering, renormalization, or pairing?', questions: ['Which electronic states and phonon modes carry the relevant coupling?', 'Which observable separates coupling strength from a bounded pairing or transport conclusion?'], evidence: 'Electron–phonon matrix elements, linewidths, self-energies, transport coefficients, superconducting gaps or transition temperatures, and experiment.', connections: [{ label: 'Foundations: Many-body perturbation theory', href: '/theory/many-body-perturbation-theory-and-quasiparticles/' }, { label: 'Methods', href: '/methods/' }] },
  { id: 'polarization-response', title: 'Polarization, dielectric, and electromechanical response', centralQuestion: 'How does a material respond to fields, strain, and long-wavelength perturbations?', questions: ['Which response is defined by the chosen boundary condition and perturbation?', 'Which path, symmetry, or reference is needed to interpret the response?'], evidence: 'Polarization changes, dielectric tensors, Born charges, piezoelectric coefficients, mode responses, and electrical or spectroscopic measurements.', connections: [{ label: 'Foundations: Berry phases and topology', href: '/theory/berry-phases-and-electronic-topology/' }, { label: 'Foundations: Linear response', href: '/theory/linear-response-and-excited-states/' }] },
  { id: 'quasiparticles-excitons', title: 'Quasiparticles, excitons, and spectroscopy', centralQuestion: 'What are the actual charged and neutral excitations, and how do they appear in measurements?', questions: ['Which excitation is charged, neutral, collective, or optical?', 'Which comparison makes the approximation and measured spectrum commensurate?'], evidence: 'Spectral functions, quasiparticle energies, optical spectra, exciton wavefunctions, screening, and photoemission or optical measurements.', connections: [{ label: 'Foundations: Many-body perturbation theory', href: '/theory/many-body-perturbation-theory-and-quasiparticles/' }, { label: 'Books', href: '/reading/books/' }] },
  { id: 'transport-scattering', title: 'Electronic transport and scattering', centralQuestion: 'How do carriers move, and what microscopic processes limit their motion?', questions: ['Which carriers and scattering channels control the measured transport regime?', 'Which model assumptions connect an electronic structure calculation to a transport observable?'], evidence: 'Band velocities, scattering rates, lifetimes, conductivities, mobilities, temperature trends, and transport measurements.', connections: [{ label: 'Foundations: Solid-state physics', href: '/theory/solid-state-physics/' }, { label: 'Methods', href: '/methods/' }] },
  { id: 'quantum-geometry-topology', title: 'Quantum geometry and topology', centralQuestion: 'Which electronic properties depend on Berry phases, global band geometry, topology, and symmetry?', questions: ['Which symmetry, gap, and electronic subspace define the proposed invariant?', 'Which bulk and boundary evidence can test the interpretation?'], evidence: 'Berry phases and curvatures, Wilson loops, topological invariants, symmetry data, boundary spectra, and experiment.', connections: [{ label: 'Foundations: Berry phases and topology', href: '/theory/berry-phases-and-electronic-topology/' }, { label: 'Methods', href: '/methods/' }] },
  { id: 'reliability-validation', title: 'Reliability, validation, and method development', centralQuestion: 'When should an electronic-structure result be trusted, and how can the approximation be improved?', questions: ['Which uncertainty is numerical, model-based, implementation-specific, or experimental?', 'What comparison would challenge rather than merely repeat the result?'], evidence: 'Convergence studies, cross-code comparisons, benchmarks, sensitivity analyses, uncertainty estimates, and experiment.', connections: [{ label: 'Foundations: Numerical analysis', href: '/theory/numerical-analysis/' }, { label: 'DFT-Research-Workflow', href: 'http://188.255.156.20/DFT-Research-Workflow/' }] },
];

export const researchTopicById = Object.fromEntries(researchTopics.map((topic) => [topic.id, topic])) as Record<string, ResearchTopic>;
