export type SourceMediaType = 'book' | 'paper' | 'software' | 'experiment';
export type SourceMediaRole = 'cover' | 'visual';

export interface SourceMediaRecord {
  id: string;
  media_role: SourceMediaRole;
  source_type: SourceMediaType;
  source_title: string;
  authors: string[];
  publication_or_publisher: string;
  year: number;
  figure_or_table_id: string;
  page_if_applicable: string | null;
  source_url: string;
  retrieval_url: string;
  local_asset: string;
  retrieved_at: string;
  usage_pages: string[];
  edition?: string;
  chapter?: string;
  section?: string;
  alt: string;
  caption: string;
  rights_note: string;
  sha256: string;
}

export type BookCoverId = 'martin' | 'sholl-steckel' | 'cohen-louie' | 'giustino' | 'liu-conceptual-dft';
export type SourceVisualId =
  | 'hohenberg-kohn-fig-1'
  | 'hohenberg-kohn-fig-2'
  | 'hedin-fig-1'
  | 'hedin-fig-2'
  | 'hedin-fig-3'
  | 'hedin-fig-4'
  | 'hedin-fig-5'
  | 'hedin-fig-6'
  | 'hedin-fig-7'
  | 'hedin-fig-8'
  | 'hedin-fig-9'
  | 'hedin-fig-10'
  | 'hedin-fig-11'
  | 'hedin-fig-12'
  | 'giustino-fig-1-2'
  | 'giustino-fig-1-3'
  | 'giustino-fig-1-4'
  | 'giustino-fig-1-5'
  | 'giustino-fig-1-6'
  | 'dftk-graphene-band-structure';

export type BookCover = SourceMediaRecord & {
  id: BookCoverId;
  media_role: 'cover';
};

export type SourceVisual = SourceMediaRecord & {
  id: SourceVisualId;
  media_role: 'visual';
};

const coverRights = 'Catalog cover image retained as a bibliographic entry point; the catalog or publisher remains the image rights authority.';
const paperExcerptRights = 'Exact crop from the cited article PDF with surrounding material trimmed. Source-linked educational excerpt; this record does not assert an open licence.';
const bookExcerptRights = 'Exact crop from the official publisher preview PDF with surrounding page material trimmed. Source-linked educational excerpt; this record does not assert an open licence.';

export const sourceMedia = {
  covers: {
    martin: {
      id: 'martin',
      media_role: 'cover',
      source_type: 'book',
      source_title: 'Electronic Structure: Basic Theory and Practical Methods',
      authors: ['Richard M. Martin'],
      publication_or_publisher: 'Cambridge University Press',
      year: 2020,
      edition: '2nd edition',
      figure_or_table_id: 'cover',
      page_if_applicable: null,
      source_url: 'https://openlibrary.org/isbn/9781108555586',
      retrieval_url: 'https://openlibrary.org/isbn/9781108555586',
      local_asset: 'media/books/martin-electronic-structure-2e.jpg',
      retrieved_at: '2026-08-11',
      usage_pages: ['/reading/books/', '/reading/books/martin/'],
      alt: 'Cover of Richard M. Martin’s Electronic Structure: Basic Theory and Practical Methods, second edition.',
      caption: 'Book cover for the Atlas Guided Reading entry.',
      rights_note: coverRights,
      sha256: 'c0a27527bd406b4677d9cce0b45c998e3b2a52a29859d797664e9719e7dbbc28',
    },
    'sholl-steckel': {
      id: 'sholl-steckel',
      media_role: 'cover',
      source_type: 'book',
      source_title: 'Density Functional Theory: A Practical Introduction',
      authors: ['David S. Sholl', 'Janice A. Steckel'],
      publication_or_publisher: 'Wiley',
      year: 2009,
      edition: '1st edition',
      figure_or_table_id: 'cover',
      page_if_applicable: null,
      source_url: 'https://openlibrary.org/isbn/9780470373170',
      retrieval_url: 'https://openlibrary.org/isbn/9780470373170',
      local_asset: 'media/books/sholl-steckel-dft-practical-introduction.jpg',
      retrieved_at: '2026-08-11',
      usage_pages: ['/reading/books/', '/reading/books/sholl-steckel/'],
      alt: 'Cover of David S. Sholl and Janice A. Steckel’s Density Functional Theory: A Practical Introduction.',
      caption: 'Book cover for the Atlas Guided Reading entry.',
      rights_note: coverRights,
      sha256: '8c18f46a32458c15c0cf14e16326b18f9a86b087d666b1cd4df953ed8cde7562',
    },
    'cohen-louie': {
      id: 'cohen-louie',
      media_role: 'cover',
      source_type: 'book',
      source_title: 'Fundamentals of Condensed Matter Physics',
      authors: ['Marvin L. Cohen', 'Steven G. Louie'],
      publication_or_publisher: 'Cambridge University Press',
      year: 2016,
      edition: '1st edition',
      figure_or_table_id: 'cover',
      page_if_applicable: null,
      source_url: 'https://openlibrary.org/isbn/9780521513319',
      retrieval_url: 'https://openlibrary.org/isbn/9780521513319',
      local_asset: 'media/books/cohen-louie-fundamentals-condensed-matter.jpg',
      retrieved_at: '2026-08-11',
      usage_pages: ['/reading/books/', '/reading/books/cohen-louie/'],
      alt: 'Cover of Marvin L. Cohen and Steven G. Louie’s Fundamentals of Condensed Matter Physics.',
      caption: 'Book cover for the Atlas Guided Reading entry.',
      rights_note: coverRights,
      sha256: '7f210fedb3ab35b1dd73b73ccc7a0b50a9f4b37d3964bcbd80d7edf015ea5e3a',
    },
    giustino: {
      id: 'giustino',
      media_role: 'cover',
      source_type: 'book',
      source_title: 'Materials Modelling Using Density Functional Theory: Properties and Predictions',
      authors: ['Feliciano Giustino'],
      publication_or_publisher: 'Oxford University Press',
      year: 2014,
      edition: '1st edition',
      figure_or_table_id: 'cover',
      page_if_applicable: null,
      source_url: 'https://books.apple.com/us/book/materials-modelling-using-density-functional-theory/id878606946',
      retrieval_url: 'https://books.apple.com/us/book/materials-modelling-using-density-functional-theory/id878606946',
      local_asset: 'media/books/giustino-materials-modelling-dft.jpg',
      retrieved_at: '2026-08-11',
      usage_pages: ['/reading/books/', '/reading/books/giustino/'],
      alt: 'Cover of Feliciano Giustino’s Materials Modelling Using Density Functional Theory: Properties and Predictions.',
      caption: 'Book cover for the Atlas Guided Reading entry.',
      rights_note: coverRights,
      sha256: '7fe1643338cd9fb276cb9cb9d26abea189d253d1f86a5646bf8e30bdc99273ca',
    },
    'liu-conceptual-dft': {
      id: 'liu-conceptual-dft',
      media_role: 'cover',
      source_type: 'book',
      source_title: 'Conceptual Density Functional Theory: Towards a New Chemical Reactivity Theory',
      authors: ['Shubin Liu'],
      publication_or_publisher: 'Wiley-VCH',
      year: 2015,
      edition: 'edited volume',
      figure_or_table_id: 'cover',
      page_if_applicable: null,
      source_url: 'https://www.wiley-vch.de/en/areas-interest/natural-sciences/chemistry-11ch/computational-chemistry-molecular-modeling-11chd/conceptual-density-functional-theory-978-3-527-34843-5',
      retrieval_url: 'https://www.wiley-vch.de/en/areas-interest/natural-sciences/chemistry-11ch/computational-chemistry-molecular-modeling-11chd/conceptual-density-functional-theory-978-3-527-34843-5',
      local_asset: 'media/books/liu-conceptual-density-functional-theory.jpg',
      retrieved_at: '2026-08-11',
      usage_pages: ['/reading/books/', '/reference/'],
      alt: 'Cover of Conceptual Density Functional Theory: Towards a New Chemical Reactivity Theory, edited by Shubin Liu.',
      caption: 'Book cover for the Atlas reference entry.',
      rights_note: coverRights,
      sha256: 'b2cbcc9e3fcb3ebd5b7e784cc85681b5d114b90ebe18c64fc7b62127017dffe4',
    },
  } satisfies Record<BookCoverId, BookCover>,
  visuals: {
    'giustino-fig-1-2': {
      id: 'giustino-fig-1-2',
      media_role: 'visual',
      source_type: 'book',
      source_title: 'Materials Modelling Using Density Functional Theory: Properties and Predictions',
      authors: ['Feliciano Giustino'],
      publication_or_publisher: 'Oxford University Press',
      year: 2014,
      figure_or_table_id: 'Fig. 1.2',
      page_if_applicable: '4',
      source_url: 'https://global.oup.com/academic/product/materials-modelling-using-density-functional-theory-9780199662449',
      retrieval_url: 'https://api.pageplace.de/preview/DT0400.9780191639425_A23590636/preview-9780191639425_A23590636.pdf',
      local_asset: 'media/source-visuals/giustino/giustino-fig-1-2.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/books/giustino/chapter-01/'],
      edition: '1st edition',
      chapter: 'Chapter 1',
      section: '§1.2.1 · exploring structures at the nanoscale',
      alt: 'Giustino 2014 Figure 1.2 showing bucky-diamond structures and calculated and experimental X-ray absorption.',
      caption: 'Figure 1.2. Bucky-diamond structures beside the calculated and experimental X-ray absorption comparison.',
      rights_note: bookExcerptRights,
      sha256: '8156a8622f6f47998b35a5d98cfa720dd9879b188f4e45ed318792a73ae881c4',
    },
    'giustino-fig-1-3': {
      id: 'giustino-fig-1-3',
      media_role: 'visual',
      source_type: 'book',
      source_title: 'Materials Modelling Using Density Functional Theory: Properties and Predictions',
      authors: ['Feliciano Giustino'],
      publication_or_publisher: 'Oxford University Press',
      year: 2014,
      figure_or_table_id: 'Fig. 1.3',
      page_if_applicable: '7',
      source_url: 'https://global.oup.com/academic/product/materials-modelling-using-density-functional-theory-9780199662449',
      retrieval_url: 'https://api.pageplace.de/preview/DT0400.9780191639425_A23590636/preview-9780191639425_A23590636.pdf',
      local_asset: 'media/source-visuals/giustino/giustino-fig-1-3.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/books/giustino/chapter-01/'],
      edition: '1st edition',
      chapter: 'Chapter 1',
      section: '§1.2.2 · superconducting materials',
      alt: 'Giustino 2014 Figure 1.3 showing the MgB2 structure and heat-capacity comparison between experiment and theory.',
      caption: 'Figure 1.3. MgB2 structure and the measured-versus-calculated heat-capacity comparison.',
      rights_note: bookExcerptRights,
      sha256: 'f8d136153716350950faa6881f3b7b605ee9bf860148200899a8200767c28b82',
    },
    'giustino-fig-1-4': {
      id: 'giustino-fig-1-4',
      media_role: 'visual',
      source_type: 'book',
      source_title: 'Materials Modelling Using Density Functional Theory: Properties and Predictions',
      authors: ['Feliciano Giustino'],
      publication_or_publisher: 'Oxford University Press',
      year: 2014,
      figure_or_table_id: 'Fig. 1.4',
      page_if_applicable: '8',
      source_url: 'https://global.oup.com/academic/product/materials-modelling-using-density-functional-theory-9780199662449',
      retrieval_url: 'https://api.pageplace.de/preview/DT0400.9780191639425_A23590636/preview-9780191639425_A23590636.pdf',
      local_asset: 'media/source-visuals/giustino/giustino-fig-1-4.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/books/giustino/chapter-01/'],
      edition: '1st edition',
      chapter: 'Chapter 1',
      section: '§1.2.3 · phase diagrams from first principles',
      alt: 'Giustino 2014 Figure 1.4 showing the epsilon-iron structure and high-pressure phase diagram.',
      caption: 'Figure 1.4. The epsilon-iron structure and calculated high-pressure melting curve with experimental points.',
      rights_note: bookExcerptRights,
      sha256: '0bb8f19bdbd0bb32089c79a3bf154172019cead213d059b6de965f0a36537060',
    },
    'giustino-fig-1-5': {
      id: 'giustino-fig-1-5',
      media_role: 'visual',
      source_type: 'book',
      source_title: 'Materials Modelling Using Density Functional Theory: Properties and Predictions',
      authors: ['Feliciano Giustino'],
      publication_or_publisher: 'Oxford University Press',
      year: 2014,
      figure_or_table_id: 'Fig. 1.5',
      page_if_applicable: '10',
      source_url: 'https://global.oup.com/academic/product/materials-modelling-using-density-functional-theory-9780199662449',
      retrieval_url: 'https://api.pageplace.de/preview/DT0400.9780191639425_A23590636/preview-9780191639425_A23590636.pdf',
      local_asset: 'media/source-visuals/giustino/giustino-fig-1-5.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/books/giustino/chapter-01/'],
      edition: '1st edition',
      chapter: 'Chapter 1',
      section: '§1.2.4 · multiscale simulations',
      alt: 'Giustino 2014 Figure 1.5 showing two atomistic snapshots of brittle fracture in silicon.',
      caption: 'Figure 1.5. Two multiscale snapshots of crack propagation in silicon.',
      rights_note: bookExcerptRights,
      sha256: 'fc3a177b4b61071265ef505c3826ed10080d0c8eb159b9fb5bf15ebbe0910778',
    },
    'giustino-fig-1-6': {
      id: 'giustino-fig-1-6',
      media_role: 'visual',
      source_type: 'book',
      source_title: 'Materials Modelling Using Density Functional Theory: Properties and Predictions',
      authors: ['Feliciano Giustino'],
      publication_or_publisher: 'Oxford University Press',
      year: 2014,
      figure_or_table_id: 'Fig. 1.6',
      page_if_applicable: '12',
      source_url: 'https://global.oup.com/academic/product/materials-modelling-using-density-functional-theory-9780199662449',
      retrieval_url: 'https://api.pageplace.de/preview/DT0400.9780191639425_A23590636/preview-9780191639425_A23590636.pdf',
      local_asset: 'media/source-visuals/giustino/giustino-fig-1-6.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/books/giustino/chapter-01/'],
      edition: '1st edition',
      chapter: 'Chapter 1',
      section: '§1.2.5 · discovering new materials',
      alt: 'Giustino 2014 Figure 1.6 showing hydrogen adsorption and stability screening for binary transition-metal alloys.',
      caption: 'Figure 1.6. Hydrogen-adsorption activity and stability screening for binary alloys.',
      rights_note: bookExcerptRights,
      sha256: '4c48fc0d5698e13bf53748218d7a572b6cac3b9ab8b2c670e23a9438d6b9c408',
    },
    'hohenberg-kohn-fig-1': {
      id: 'hohenberg-kohn-fig-1',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'Inhomogeneous Electron Gas',
      authors: ['Pierre Hohenberg', 'Walter Kohn'],
      publication_or_publisher: 'Physical Review 136, American Physical Society',
      year: 1964,
      figure_or_table_id: 'Fig. 1',
      page_if_applicable: 'B867',
      source_url: 'https://doi.org/10.1103/PhysRev.136.B864',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.136.B864/fulltext',
      local_asset: 'media/source-visuals/hohenberg-kohn-fig-1.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hohenberg-kohn-1964/', '/theory/density-functional-theory-foundations/'],
      section: 'Part II · almost constant density',
      alt: 'Original Hohenberg–Kohn 1964 Figure 1 showing the uniform-electron-gas response curve.',
      caption: 'Figure 1. The uniform-electron-gas response plotted against the scaled perturbation wavevector.',
      rights_note: paperExcerptRights,
      sha256: '1ec28063c7d8b07fd8ae70fbfb9cf7912f5158bc5091c0e98d0dad99a4ef363c',
    },
    'hohenberg-kohn-fig-2': {
      id: 'hohenberg-kohn-fig-2',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'Inhomogeneous Electron Gas',
      authors: ['Pierre Hohenberg', 'Walter Kohn'],
      publication_or_publisher: 'Physical Review 136, American Physical Society',
      year: 1964,
      figure_or_table_id: 'Fig. 2',
      page_if_applicable: 'B868',
      source_url: 'https://doi.org/10.1103/PhysRev.136.B864',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.136.B864/fulltext',
      local_asset: 'media/source-visuals/hohenberg-kohn-fig-2.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hohenberg-kohn-1964/', '/theory/density-functional-theory-foundations/'],
      section: 'Part II · almost constant density',
      alt: 'Original Hohenberg–Kohn 1964 Figure 2 showing the response kernel.',
      caption: 'Figure 2. The response kernel whose feature near twice the Fermi wavevector limits a local expansion.',
      rights_note: paperExcerptRights,
      sha256: '73d8505ebb10b1001bd0042d817d4800f365481e7685ee038764b259f2d729cb',
    },
    'hedin-fig-1': {
      id: 'hedin-fig-1',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 1',
      page_if_applicable: 'A798',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin-fig-1.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/', '/theory/many-body-perturbation-theory-and-quasiparticles/'],
      section: 'diagrammatic expansion of the self-energy',
      alt: 'Original Hedin 1965 Figure 1 showing the diagrammatic expansion of the self-energy.',
      caption: 'Figure 1. Hedin’s original diagrammatic expansion for the self-energy.',
      rights_note: paperExcerptRights,
      sha256: '5533b480ee6231a5889412e8cf78fbdf3d129db265f90160c82fe457c888ae93',
    },
    'hedin-fig-2': {
      id: 'hedin-fig-2',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 2',
      page_if_applicable: 'A798',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin-fig-2.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/', '/theory/many-body-perturbation-theory-and-quasiparticles/'],
      section: 'diagrammatic expansion of the polarization',
      alt: 'Original Hedin 1965 Figure 2 showing the diagrammatic expansion of the polarization.',
      caption: 'Figure 2. Hedin’s original diagrammatic expansion for the polarization.',
      rights_note: paperExcerptRights,
      sha256: '0f509acb272bff4caf198e13d64d111696e52126b948b1d14a79006c8848fdbb',
    },
    'hedin-fig-3': {
      id: 'hedin-fig-3',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 3',
      page_if_applicable: 'A805',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin/hedin-fig-3.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/'],
      section: 'pair correlation function',
      alt: 'Original Hedin 1965 Figure 3 showing the pair correlation function for an electron gas.',
      caption: 'Figure 3. Pair correlation function for an electron gas.',
      rights_note: paperExcerptRights,
      sha256: '3296a7e118b4f7f0fabd887df76debf6ea0d54f4bb71b01a189eb0ce25336063',
    },
    'hedin-fig-4': {
      id: 'hedin-fig-4',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 4',
      page_if_applicable: 'A805',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin/hedin-fig-4.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/'],
      section: 'radially weighted pair correlation function',
      alt: 'Original Hedin 1965 Figure 4 showing the radially weighted pair correlation function.',
      caption: 'Figure 4. Radially weighted pair-correlation curves whose area is normalized to minus one.',
      rights_note: paperExcerptRights,
      sha256: 'ceae92478ee08b4deb05fab3a68e239e7e73055f3883e9363855bf9d41205292',
    },
    'hedin-fig-5': {
      id: 'hedin-fig-5',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 5',
      page_if_applicable: 'A805',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin/hedin-fig-5.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/'],
      section: 'ladder-bubble diagrams',
      alt: 'Original Hedin 1965 Figure 5 showing the ladder-bubble diagram series.',
      caption: 'Figure 5. Ladder-bubble diagrams used in the polarization expansion.',
      rights_note: paperExcerptRights,
      sha256: 'c165db731eab52443502124638a2e1cf072cf0fa50dc165ee9def18c0df46416',
    },
    'hedin-fig-6': {
      id: 'hedin-fig-6',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 6',
      page_if_applicable: 'A806',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin/hedin-fig-6.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/'],
      section: 'real-space screening factor',
      alt: 'Original Hedin 1965 Figure 6 comparing screening factors for the electron gas.',
      caption: 'Figure 6. Screening factor of the electron-gas potential compared across approximations.',
      rights_note: paperExcerptRights,
      sha256: '5a038ab3f37d994fd3e8371178f1b6be71d39c24f5e8d48d621345f4b304ce92',
    },
    'hedin-fig-7': {
      id: 'hedin-fig-7',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 7',
      page_if_applicable: 'A807',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin/hedin-fig-7.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/'],
      section: 'potential energy of the electron gas',
      alt: 'Original Hedin 1965 Figure 7 showing potential energy versus the electron-gas density parameter.',
      caption: 'Figure 7. Potential energy of an electron gas as a function of the density parameter.',
      rights_note: paperExcerptRights,
      sha256: '1d4ebc6699110cac03e0535428c184c08ee7a37db9dd2c86137aedc2dca5bf78',
    },
    'hedin-fig-8': {
      id: 'hedin-fig-8',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 8',
      page_if_applicable: 'A808',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin/hedin-fig-8.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/'],
      section: 'total energy of the electron gas',
      alt: 'Original Hedin 1965 Figure 8 showing total energy curves for an electron gas.',
      caption: 'Figure 8. Total energy of an electron gas compared with the electron-lattice energy.',
      rights_note: paperExcerptRights,
      sha256: 'ebcc16cd5cd4c3f4b513b0bafc31f2965de56c9f7e3c07f25f02840c509e8621',
    },
    'hedin-fig-9': {
      id: 'hedin-fig-9',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 9',
      page_if_applicable: 'A811',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin/hedin-fig-9.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/'],
      section: 'quasiparticle energy',
      alt: 'Original Hedin 1965 Figure 9 showing quasiparticle energy as a function of momentum.',
      caption: 'Figure 9. Quasiparticle energy as a function of momentum, with free, exchange-correlation, and approximation curves.',
      rights_note: paperExcerptRights,
      sha256: '76d2a30ac4fe614236014169449dee9f05367d9b6e8ed29aa6241f2cfbd864a1',
    },
    'hedin-fig-10': {
      id: 'hedin-fig-10',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 10',
      page_if_applicable: 'A813',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin/hedin-fig-10.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/'],
      section: 'nonlocal self-energy operator',
      alt: 'Original Hedin 1965 Figure 10 showing the self-energy operator as a nonlocal potential.',
      caption: 'Figure 10. Self-energy operator represented as a nonlocal potential.',
      rights_note: paperExcerptRights,
      sha256: '1c29757fee3f173839e10b82e6dca703ad5abd19394c8cdc08ccb73067adc3dc',
    },
    'hedin-fig-11': {
      id: 'hedin-fig-11',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 11',
      page_if_applicable: 'A816',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin/hedin-fig-11.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/'],
      section: 'quasiparticle interaction',
      alt: 'Original Hedin 1965 Figure 11 showing the quasiparticle interaction.',
      caption: 'Figure 11. Quasiparticle interaction plotted against the angle between momenta.',
      rights_note: paperExcerptRights,
      sha256: '39261b8d759ae193a4faca01c0db5cc8b285e5ca5bd0b340fd74cfdced1cd741',
    },
    'hedin-fig-12': {
      id: 'hedin-fig-12',
      media_role: 'visual',
      source_type: 'paper',
      source_title: 'New Method for Calculating the One-Particle Green’s Function with Application to the Electron-Gas Problem',
      authors: ['Lars Hedin'],
      publication_or_publisher: 'Physical Review 139, American Physical Society',
      year: 1965,
      figure_or_table_id: 'Fig. 12',
      page_if_applicable: 'A817',
      source_url: 'https://doi.org/10.1103/PhysRev.139.A796',
      retrieval_url: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.139.A796/fulltext',
      local_asset: 'media/source-visuals/hedin/hedin-fig-12.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/reading/literature/hedin-1965/'],
      section: 'specific heat of the electron gas',
      alt: 'Original Hedin 1965 Figure 12 showing specific heat of an electron gas.',
      caption: 'Figure 12. Specific heat of an electron gas relative to a non-interacting or Sommerfeld gas.',
      rights_note: paperExcerptRights,
      sha256: '9a08cfc8332ec7127a74c1330aee60163814f13bab510d497c8abb4eb106851d',
    },
    'dftk-graphene-band-structure': {
      id: 'dftk-graphene-band-structure',
      media_role: 'visual',
      source_type: 'software',
      source_title: 'Graphene band structure example',
      authors: ['DFTK.jl contributors'],
      publication_or_publisher: 'DFTK.jl official documentation',
      year: 2026,
      figure_or_table_id: 'rendered band-structure plot',
      page_if_applicable: 'web example',
      source_url: 'https://docs.dftk.org/stable/examples/graphene/',
      retrieval_url: 'https://docs.dftk.org/stable/examples/graphene/',
      local_asset: 'media/source-visuals/dftk-graphene-band-structure.png',
      retrieved_at: '2026-08-12',
      usage_pages: ['/theory/solid-state-physics/'],
      section: 'calculated band structure',
      alt: 'DFTK graphene band-structure calculation along the Gamma–M–K–Gamma path.',
      caption: 'Calculated band structure from the official DFTK graphene example, showing the selected Γ–M–K–Γ path.',
      rights_note: 'Captured from official software documentation for attribution and method orientation; this is an example calculation, not a new Atlas benchmark or a universal graphene reference result.',
      sha256: '6e0c8aea5cc51898b38c2ea1d72cdfd322421938ad3db34b73d6caf640caa6f5',
    },
  } satisfies Record<SourceVisualId, SourceVisual>,
} as const;

export const bookCovers = sourceMedia.covers;
export const sourceVisuals = sourceMedia.visuals;
